---
name: rg2_flutter_getx
description: RG2 write with flutter and GetX plugin
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.7.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  floor: ^0.18.0
  get: ^3.24.0
  get_storage: ^1.4.0
  flutter_material_color_picker: ^1.0.5
  flutter_slidable: ^0.5.7
  flutter_svg: ^0.19.1
  html: ^0.14.0+4
  csslib: ^0.16.2
  css_colors: ^1.0.2
  webview_flutter: ^1.0.7
  url_launcher: ^5.7.10
  implicitly_animated_reorderable_list: ^0.3.2
  youtube_player_flutter: ^7.0.0+7
  carousel_slider: ^3.0.0
  assets_audio_player: ^2.0.13+7
  matrix4_transform: ^1.1.7
  cupertino_icons: ^1.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  floor_generator: ^0.18.0
  build_runner: ^1.11.1
flutter:
  uses-material-design: true
  assets:
  - assets/images/trainers/timer/
  - assets/images/trainers/
  - assets/images/main_other3x3/ghost/
  - assets/images/main3x3/g2f/
  - assets/images/main_other/keyhole/
  - assets/images/main_other/square/
  - assets/images/main_other/pyraminx/
  - assets/images/main_other/
  - assets/images/main_skewb/ivy/
  - assets/images/main_other3x3/cylinder/
  - assets/images/big_main/
  - assets/images/main_2x2/begin_2x2/
  - assets/images/main_other3x3/penrose/
  - assets/images/main_2x2/
  - assets/images/main3x3/main_f2l/
  - assets/images/main_skewb/container/
  - assets/images/main_2x2/cll/
  - assets/images/main_2x2/ortega/
  - assets/images/advices/
  - assets/images/main_other3x3/tw_cube/
  - assets/images/main3x3/coll/
  - assets/images/main_other3x3/gear/
  - assets/images/main_other/cuboid_2x2x3/
  - assets/images/main_other/pentacle/
  - assets/images/azbuka/basic_3x3/
  - assets/images/main_other3x3/pyramorphix/
  - assets/images/main_skewb/redi/
  - assets/images/main_other/main_pyraminx/
  - assets/images/big_main/begin_4x4/
  - assets/images/main_skewb/skewb/
  - assets/images/azbuka/basic_5x5/
  - assets/images/main_other3x3/fisher/
  - assets/images/main3x3/oll/
  - assets/images/main_other3x3/mirror/
  - assets/images/main_2x2/advanced_2x2/
  - assets/images/main3x3/rozov/
  - assets/images/main_other/megaminx/
  - assets/images/main3x3/roux/
  - assets/images/main3x3/cross/
  - assets/images/main_skewb/tw_skewb/
  - assets/images/main3x3/begin/
  - assets/images/big_main/yau_4x4/
  - assets/images/main_skewb/
  - assets/images/azbuka/basic_container/
  - assets/images/main3x3/
  - assets/images/main_other/sq_star/
  - assets/images/azbuka/basic_ivy/
  - assets/images/main3x3/f2l/
  - assets/images/main3x3/patterns/
  - assets/images/azbuka/basic_redi/
  - assets/images/main_other3x3/prisma/
  - assets/images/main3x3/pll/
  - assets/images/big_main/blind_4x4/
  - assets/images/azbuka/basic_clover/
  - assets/images/azbuka/basic_4x4/
  - assets/images/main_other3x3/sudoku/
  - assets/images/big_main/begin_5x5/
  - assets/images/main_other3x3/
  - assets/images/
  - assets/images/azbuka/basic_skewb/
  - assets/images/main_other3x3/axis/
  - assets/images/azbuka/basic_square/
  - assets/images/main_skewb/clover/
  - assets/images/main_other/pyraminx_4x4/
  - assets/images/main3x3/blind/
  - assets/images/main3x3/int_f2l/
  - assets/images/main_other3x3/cub_3x3x2/
  - assets/images/main3x3/accel/
  - assets/images/main_other3x3/windmill/
  - assets/images/main_other3x3/brick/
  - assets/images/icons/
  - assets/icons/
  - assets/images/azbuka/basic_pyraminx/
  - assets/images/azbuka/basic_pyraminx_4x4/
  - assets/images/main3x3/adv_f2l/
  - assets/images/big_main/big_cubes/
  - assets/sounds/
