name: rg2
description: RG2

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 4.210527.1+421

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # SQL Database
  floor: ^1.1.0
  # DI + StateManagement
  get: ^4.1.4
  # Работаем с SharedPreferences
  get_storage: ^2.0.2
  # Окно выбора цвета
  flutter_material_color_picker: ^1.0.5
  # возможность смахивать элементы List
  flutter_slidable: ^0.6.0
  # Добавляем возможность работы с SVG
  flutter_svg: ^0.22.0

  # Отображаем текст в html
  # Plugin for parsing html
  html: ^0.15.0
  # Plugins for parsing css
  csslib: ^0.17.0
  css_colors: ^1.1.1
  # Plugins for rendering the <video> tag.
  # video_player: ^1.0.1
  # chewie: ^0.12.2
  # Plugin for rendering the <iframe> tag.
  webview_flutter: ^2.0.8
  # Plugins for rendering the <audio> tag.
  # chewie_audio: ^1.1.1

  # Открываем ссылки во внешних программах (браузерах, почте и т.д.)
  url_launcher: ^6.0.2

  # Плагин чтобы сделать элементы списка перемещаемыми и смахиваемыми (Reorderable & Slidable)
  implicitly_animated_reorderable_list: ^0.4.0

  # YouTube Plugin
  youtube_player_flutter: ^8.0.0
#  youtube_plyr_iframe: ^2.0.3

  #Слайдер для картинок списка советов по работе с программой
  carousel_slider: ^3.0.0

  # Поддержка звука, для метронома в таймере
  #assets_audio_player: ^2.0.14
  audioplayers: ^0.18.3

  # Для удобной работы с датой/временем
  intl: ^0.17.0

  # Индикатор оставшегося времени на ответ
  percent_indicator: ^3.0.1

  # Firebase + google sign in
  firebase_core: ^1.2.0
  firebase_auth: ^1.2.0
  cloud_firestore: ^2.2.0
  google_sign_in: ^5.0.4
  apple_sign_in: ^0.1.0

  # Валидаторы для проверки полей ввода
  form_field_validator: ^1.1.0

  # Красивые кнопки аутентификации
  auth_buttons: ^1.0.1+3

  # Проверка соединения https://pub.dev/packages/connectivity
  connectivity: ^3.0.6

  # Покупки в приложении
  in_app_purchase: ^1.0.1

  # Реклама в приложении
  google_mobile_ads: ^0.12.2

  # Получение версии приложения в коде
  package_info: ^2.0.2

  # красивый свитч для смены темы
  flutter_switch: ^0.3.1

  cupertino_icons: ^1.0.3

  # icon of google
  flutter_vector_icons: ^1.0.0

  # Автосоздание иконок для приложения
  flutter_launcher_icons: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # SQL генератор, т.к. нужна кодогенерация + build runner
  floor_generator: ^1.1.0
  build_runner: ^2.0.4

flutter_icons:
  android: "ic_launcher"
  ios: true

  image_path: "assets/icons/icon_1024.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/ads/
    - assets/images/trainers/pll_cube_2side/
    - assets/images/trainers/pll_cube_3side/
    - assets/images/trainers/timer/
    - assets/images/trainers/
    - assets/images/main_other3x3/ghost/
    - assets/images/main3x3/g2f/
    - assets/images/main_other/keyhole/
    - assets/images/main_other/square/
    - assets/images/main_other/pyraminx/
    - assets/images/main_other/
    - assets/images/main_skewb/ivy/
    - assets/images/main_other3x3/cylinder/
    - assets/images/big_main/
    - assets/images/main_2x2/begin_2x2/
    - assets/images/main_other3x3/penrose/
    - assets/images/main_2x2/
    - assets/images/main3x3/main_f2l/
    - assets/images/main_skewb/container/
    - assets/images/main_2x2/cll/
    - assets/images/main_2x2/ortega/
    - assets/images/advices/
    - assets/images/main_other3x3/tw_cube/
    - assets/images/main3x3/coll/
    - assets/images/main_other3x3/gear/
    - assets/images/main_other/cuboid_2x2x3/
    - assets/images/main_other/pentacle/
    - assets/images/azbuka/basic_3x3/
    - assets/images/main_other3x3/pyramorphix/
    - assets/images/main_skewb/redi/
    - assets/images/main_other/main_pyraminx/
    - assets/images/big_main/begin_4x4/
    - assets/images/main_skewb/skewb/
    - assets/images/azbuka/basic_5x5/
    - assets/images/main_other3x3/fisher/
    - assets/images/main3x3/oll/
    - assets/images/main_other3x3/mirror/
    - assets/images/main_2x2/advanced_2x2/
    - assets/images/main3x3/rozov/
    - assets/images/main_other/megaminx/
    - assets/images/main3x3/roux/
    - assets/images/main3x3/cross/
    - assets/images/main_skewb/tw_skewb/
    - assets/images/main3x3/begin/
    - assets/images/big_main/yau_4x4/
    - assets/images/main_skewb/
    - assets/images/azbuka/basic_container/
    - assets/images/main3x3/
    - assets/images/main_other/sq_star/
    - assets/images/azbuka/basic_ivy/
    - assets/images/main3x3/f2l/
    - assets/images/main3x3/patterns/
    - assets/images/azbuka/basic_redi/
    - assets/images/main_other3x3/prisma/
    - assets/images/main3x3/pll/
    - assets/images/big_main/blind_4x4/
    - assets/images/azbuka/basic_clover/
    - assets/images/azbuka/basic_4x4/
    - assets/images/main_other3x3/sudoku/
    - assets/images/big_main/begin_5x5/
    - assets/images/main_other3x3/
    - assets/images/
    - assets/images/azbuka/basic_skewb/
    - assets/images/main_other3x3/axis/
    - assets/images/azbuka/basic_square/
    - assets/images/main_skewb/clover/
    - assets/images/main_other/pyraminx_4x4/
    - assets/images/main3x3/blind/
    - assets/images/main3x3/int_f2l/
    - assets/images/main_other3x3/cub_3x3x2/
    - assets/images/main3x3/accel/
    - assets/images/main_other3x3/windmill/
    - assets/images/main_other3x3/brick/
    - assets/images/icons/
    - assets/icons/
    - assets/images/azbuka/basic_pyraminx/
    - assets/images/azbuka/basic_pyraminx_4x4/
    - assets/images/main3x3/adv_f2l/
    - assets/images/big_main/big_cubes/
    - assets/sounds/
    - assets/images/trainers/pll_trainer/
    - assets/images/trainers/azbuka_cube/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
